from __future__ import annotations

import argparse
from pathlib import Path


CONFIGS = (
    {
        "selection": 1,
        "suffix": "1k_12",
        "g_path": "c/build_g/G_1_2_1024.mat",
        "info_length": 1024,
        "transmitted_length": 2048,
        "full_length": 2560,
        "row_blocks": 8,
        "col_blocks": 8,
        "block_size": 128,
        "sim_time_us": 2300,
    },
    {
        "selection": 2,
        "suffix": "4k_12",
        "g_path": "c/build_g/G_1_2_4096.mat",
        "info_length": 4096,
        "transmitted_length": 8192,
        "full_length": 10240,
        "row_blocks": 8,
        "col_blocks": 8,
        "block_size": 512,
        "sim_time_us": 10000,
    },
    {
        "selection": 3,
        "suffix": "16k_12",
        "g_path": "c/build_g/G_1_2_16384.mat",
        "info_length": 16384,
        "transmitted_length": 32768,
        "full_length": 40960,
        "row_blocks": 8,
        "col_blocks": 8,
        "block_size": 2048,
        "sim_time_us": 40000,
    },
    {
        "selection": 4,
        "suffix": "1k_23",
        "g_path": "c/build_g/G_2_3_1024.mat",
        "info_length": 1024,
        "transmitted_length": 1536,
        "full_length": 1792,
        "row_blocks": 16,
        "col_blocks": 8,
        "block_size": 64,
        "sim_time_us": 1800,
    },
    {
        "selection": 5,
        "suffix": "4k_23",
        "g_path": "c/build_g/G_2_3_4096.mat",
        "info_length": 4096,
        "transmitted_length": 6144,
        "full_length": 7168,
        "row_blocks": 16,
        "col_blocks": 8,
        "block_size": 256,
        "sim_time_us": 8000,
    },
    {
        "selection": 6,
        "suffix": "16k_23",
        "g_path": "c/build_g/G_2_3_16384.mat",
        "info_length": 16384,
        "transmitted_length": 24576,
        "full_length": 28672,
        "row_blocks": 16,
        "col_blocks": 8,
        "block_size": 1024,
        "sim_time_us": 32000,
    },
    {
        "selection": 7,
        "suffix": "1k_45",
        "g_path": "c/build_g/G_4_5_1024.mat",
        "info_length": 1024,
        "transmitted_length": 1280,
        "full_length": 1408,
        "row_blocks": 32,
        "col_blocks": 8,
        "block_size": 32,
        "sim_time_us": 1600,
    },
    {
        "selection": 8,
        "suffix": "4k_45",
        "g_path": "c/build_g/G_4_5_4096.mat",
        "info_length": 4096,
        "transmitted_length": 5120,
        "full_length": 5632,
        "row_blocks": 32,
        "col_blocks": 8,
        "block_size": 128,
        "sim_time_us": 6000,
    },
    {
        "selection": 9,
        "suffix": "16k_45",
        "g_path": "c/build_g/G_4_5_16384.mat",
        "info_length": 16384,
        "transmitted_length": 20480,
        "full_length": 22528,
        "row_blocks": 32,
        "col_blocks": 8,
        "block_size": 512,
        "sim_time_us": 24000,
    },
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate version6 LDPC source and simulation artifacts.")
    parser.add_argument(
        "targets",
        nargs="*",
        help="Optional configuration suffixes to generate, for example 1k_12 4k_23. Defaults to all 9 configs.",
    )
    return parser.parse_args()


def emit_config_package(config: dict[str, int | str], output_path: Path) -> None:
    info_length = int(config["info_length"])
    transmitted_length = int(config["transmitted_length"])
    full_length = int(config["full_length"])
    parity_length = transmitted_length - info_length
    row_blocks = int(config["row_blocks"])
    col_blocks = int(config["col_blocks"])
    block_size = int(config["block_size"])
    suffix = str(config["suffix"])

    lines = [
        "library ieee;",
        "use ieee.std_logic_1164.all;",
        "",
        f"package ldpc_encoder_{suffix}_config_pkg is",
        f"  constant LDPC_K : natural := {info_length};",
        f"  constant LDPC_N : natural := {transmitted_length};",
        f"  constant LDPC_TOTAL_LENGTH : natural := {full_length};",
        f"  constant LDPC_M : natural := {full_length - transmitted_length};",
        "",
        f"  constant LDPC_QC_ROW_BLOCKS : natural := {row_blocks};",
        f"  constant LDPC_QC_COL_BLOCKS : natural := {col_blocks};",
        f"  constant LDPC_QC_BLOCK_SIZE : natural := {block_size};",
        f"  constant LDPC_QC_PARITY_LENGTH : natural := {parity_length};",
        f"end package ldpc_encoder_{suffix}_config_pkg;",
        "",
    ]
    output_path.write_text("\n".join(lines), encoding="ascii")


def emit_wrapper(config: dict[str, int | str], output_path: Path) -> None:
    suffix = str(config["suffix"])
    suffix_upper = suffix.upper()

    lines = [
        "library ieee;",
        "use ieee.std_logic_1164.all;",
        "",
        "library work;",
        "use work.ldpc_encoder_common_pkg.all;",
        f"use work.ldpc_encoder_{suffix}_config_pkg.all;",
        f"use work.ldpc_encoder_{suffix}_qc_rom_pkg.all;",
        "",
        f"entity ldpc_encoder_{suffix} is",
        "  port (",
        "    clock_i        : in std_logic;",
        "    reset_i        : in std_logic;",
        "    data_i         : in std_logic;",
        "    data_en_i      : in std_logic;",
        "    data_start_i   : in std_logic;",
        "    data_o         : out std_logic;",
        "    data_en_o      : out std_logic;",
        "    data_start_o   : out std_logic;",
        "    data_message_o : out std_logic;",
        "    data_parity_o  : out std_logic",
        "  );",
        f"end entity ldpc_encoder_{suffix};",
        "",
        f"architecture rtl of ldpc_encoder_{suffix} is",
        "  signal rom_row_block_s : natural range 0 to LDPC_QC_ROW_BLOCKS - 1 := 0;",
        "  signal rom_data_s : t_std_logic_vector_array(0 to LDPC_QC_COL_BLOCKS - 1)(LDPC_QC_BLOCK_SIZE - 1 downto 0) := (others => (others => '0'));",
        "begin",
        "  rom_generate : for rom_index in 0 to LDPC_QC_COL_BLOCKS - 1 generate",
        "  begin",
        f"    rom_data_s(rom_index) <= C_LDPC_QC_ROM_BANK_{suffix_upper}(rom_index)(rom_row_block_s);",
        "  end generate rom_generate;",
        "",
        "  core_inst : entity work.ldpc_qc_encoder_core",
        "    generic map (",
        "      G_LDPC_K             => LDPC_K,",
        "      G_LDPC_N             => LDPC_N,",
        "      G_LDPC_QC_ROW_BLOCKS => LDPC_QC_ROW_BLOCKS,",
        "      G_LDPC_QC_COL_BLOCKS => LDPC_QC_COL_BLOCKS,",
        "      G_LDPC_QC_BLOCK_SIZE => LDPC_QC_BLOCK_SIZE",
        "    )",
        "    port map (",
        "      clock_i         => clock_i,",
        "      reset_i         => reset_i,",
        "      data_i          => data_i,",
        "      data_en_i       => data_en_i,",
        "      data_start_i    => data_start_i,",
        "      rom_row_block_o => rom_row_block_s,",
        "      rom_data_i      => rom_data_s,",
        "      data_o          => data_o,",
        "      data_en_o       => data_en_o,",
        "      data_start_o    => data_start_o,",
        "      data_message_o  => data_message_o,",
        "      data_parity_o   => data_parity_o",
        "    );",
        "end architecture rtl;",
        "",
    ]
    output_path.write_text("\n".join(lines), encoding="ascii")


def emit_standard_testbench(config: dict[str, int | str], output_path: Path) -> None:
    suffix = str(config["suffix"])
    lines = [
        "library ieee;",
        "use ieee.std_logic_1164.all;",
        "use std.env.all;",
        "",
        "library work;",
        f"use work.ldpc_encoder_{suffix}_config_pkg.all;",
        f"use work.ldpc_encoder_{suffix}_vectors_pkg.all;",
        "",
        f"entity tb_ldpc_encoder_{suffix} is",
        f"end entity tb_ldpc_encoder_{suffix};",
        "",
        f"architecture sim of tb_ldpc_encoder_{suffix} is",
        "  constant CLK_PERIOD : time := 10 ns;",
        "",
        "  signal clock_i            : std_logic := '0';",
        "  signal reset_i            : std_logic := '1';",
        "  signal data_i             : std_logic := '0';",
        "  signal data_en_i          : std_logic := '0';",
        "  signal data_start_i       : std_logic := '0';",
        "  signal data_o             : std_logic := '0';",
        "  signal data_en_o          : std_logic := '0';",
        "  signal data_start_o       : std_logic := '0';",
        "  signal data_message_o     : std_logic := '0';",
        "  signal data_parity_o      : std_logic := '0';",
        "  signal observed_index     : natural range 0 to LDPC_N := 0;",
        "  signal frame_done         : std_logic := '0';",
        "  signal cycle_counter      : natural := 0;",
        "  signal input_start_cycle  : natural := 0;",
        "  signal first_output_cycle : natural := 0;",
        "  signal frame_done_cycle   : natural := 0;",
        "  signal input_started      : std_logic := '0';",
        "  signal first_output_seen  : std_logic := '0';",
        "begin",
        "  clock_i <= not clock_i after CLK_PERIOD / 2;",
        "",
        f"  dut : entity work.ldpc_encoder_{suffix}",
        "    port map (",
        "      clock_i        => clock_i,",
        "      reset_i        => reset_i,",
        "      data_i         => data_i,",
        "      data_en_i      => data_en_i,",
        "      data_start_i   => data_start_i,",
        "      data_o         => data_o,",
        "      data_en_o      => data_en_o,",
        "      data_start_o   => data_start_o,",
        "      data_message_o => data_message_o,",
        "      data_parity_o  => data_parity_o",
        "    );",
        "",
        "  reset_process : process",
        "  begin",
        "    reset_i <= '1';",
        "    wait for 5 * CLK_PERIOD;",
        "    wait until rising_edge(clock_i);",
        "    reset_i <= '0';",
        "    wait;",
        "  end process;",
        "",
        "  stimulus : process",
        "  begin",
        "    wait until reset_i = '0';",
        "    wait until rising_edge(clock_i);",
        "",
        "    for bit_index in 0 to LDPC_K - 1 loop",
        "      data_i <= MESSAGE_BITS(bit_index);",
        "      data_en_i <= '1';",
        "      if bit_index = 0 then",
        "        data_start_i <= '1';",
        "      else",
        "        data_start_i <= '0';",
        "      end if;",
        "      wait until rising_edge(clock_i);",
        "    end loop;",
        "",
        "    data_i <= '0';",
        "    data_en_i <= '0';",
        "    data_start_i <= '0';",
        "",
        "    wait until frame_done = '1';",
        "    wait until rising_edge(clock_i);",
        "    report \"TB LATENCY: total_cycles=\" & integer'image(frame_done_cycle - input_start_cycle) &",
        "           \", output_start_cycles=\" & integer'image(first_output_cycle - input_start_cycle) &",
        "           \", output_stream_cycles=\" & integer'image(frame_done_cycle - first_output_cycle + 1)",
        "      severity note;",
        "    report \"TB PASS: encoded frame matches reference vector\" severity note;",
        "    finish;",
        "  end process;",
        "",
        "  monitor : process (clock_i)",
        "  begin",
        "    if rising_edge(clock_i) then",
        "      if reset_i = '1' then",
        "        observed_index <= 0;",
        "        frame_done <= '0';",
        "        cycle_counter <= 0;",
        "        input_start_cycle <= 0;",
        "        first_output_cycle <= 0;",
        "        frame_done_cycle <= 0;",
        "        input_started <= '0';",
        "        first_output_seen <= '0';",
        "      else",
        "        cycle_counter <= cycle_counter + 1;",
        "",
        "        if input_started = '0' and data_en_i = '1' and data_start_i = '1' then",
        "          input_start_cycle <= cycle_counter;",
        "          input_started <= '1';",
        "        end if;",
        "",
        "        if first_output_seen = '0' and data_en_o = '1' then",
        "          first_output_cycle <= cycle_counter;",
        "          first_output_seen <= '1';",
        "        end if;",
        "",
        "        if data_en_o = '1' then",
        "          assert observed_index < LDPC_N",
        "            report \"Observed more output bits than expected\"",
        "            severity failure;",
        "          assert data_o = EXPECTED_CODEWORD(observed_index)",
        "            report \"Encoded bit mismatch at position \" & integer'image(observed_index)",
        "            severity failure;",
        "",
        "          if observed_index = 0 then",
        "            assert data_start_o = '1'",
        "              report \"data_start_o must be asserted on the first output bit\"",
        "              severity failure;",
        "          else",
        "            assert data_start_o = '0'",
        "              report \"data_start_o must only pulse on the first output bit\"",
        "              severity failure;",
        "          end if;",
        "",
        "          if observed_index < LDPC_K then",
        "            assert data_message_o = '1' and data_parity_o = '0'",
        "              report \"Message/parity qualifiers are incorrect during message output\"",
        "              severity failure;",
        "          else",
        "            assert data_message_o = '0' and data_parity_o = '1'",
        "              report \"Message/parity qualifiers are incorrect during parity output\"",
        "              severity failure;",
        "          end if;",
        "",
        "          if observed_index = LDPC_N - 1 then",
        "            observed_index <= LDPC_N;",
        "            frame_done <= '1';",
        "            frame_done_cycle <= cycle_counter;",
        "          else",
        "            observed_index <= observed_index + 1;",
        "          end if;",
        "        end if;",
        "      end if;",
        "    end if;",
        "  end process;",
        "end architecture sim;",
        "",
    ]
    output_path.write_text("\n".join(lines), encoding="ascii")


def emit_vunit_testbench(config: dict[str, int | str], output_path: Path) -> None:
    suffix = str(config["suffix"])
    lines = [
        "library ieee;",
        "use ieee.std_logic_1164.all;",
        "",
        "library vunit_lib;",
        "context vunit_lib.vunit_context;",
        "",
        "library work;",
        f"use work.ldpc_encoder_{suffix}_config_pkg.all;",
        f"use work.ldpc_encoder_{suffix}_vectors_pkg.all;",
        "",
        f"entity tb_vunit_ldpc_encoder_{suffix} is",
        "  generic (",
        "    runner_cfg : string",
        "  );",
        f"end entity tb_vunit_ldpc_encoder_{suffix};",
        "",
        f"architecture sim of tb_vunit_ldpc_encoder_{suffix} is",
        "  constant CLK_PERIOD : time := 10 ns;",
        "",
        "  signal clock_i            : std_logic := '0';",
        "  signal reset_i            : std_logic := '1';",
        "  signal data_i             : std_logic := '0';",
        "  signal data_en_i          : std_logic := '0';",
        "  signal data_start_i       : std_logic := '0';",
        "  signal data_o             : std_logic := '0';",
        "  signal data_en_o          : std_logic := '0';",
        "  signal data_start_o       : std_logic := '0';",
        "  signal data_message_o     : std_logic := '0';",
        "  signal data_parity_o      : std_logic := '0';",
        "  signal observed_index     : natural range 0 to LDPC_N := 0;",
        "  signal frame_done         : std_logic := '0';",
        "  signal cycle_counter      : natural := 0;",
        "  signal input_start_cycle  : natural := 0;",
        "  signal first_output_cycle : natural := 0;",
        "  signal frame_done_cycle   : natural := 0;",
        "  signal input_started      : std_logic := '0';",
        "  signal first_output_seen  : std_logic := '0';",
        "begin",
        "  clock_i <= not clock_i after CLK_PERIOD / 2;",
        "",
        f"  dut : entity work.ldpc_encoder_{suffix}",
        "    port map (",
        "      clock_i        => clock_i,",
        "      reset_i        => reset_i,",
        "      data_i         => data_i,",
        "      data_en_i      => data_en_i,",
        "      data_start_i   => data_start_i,",
        "      data_o         => data_o,",
        "      data_en_o      => data_en_o,",
        "      data_start_o   => data_start_o,",
        "      data_message_o => data_message_o,",
        "      data_parity_o  => data_parity_o",
        "    );",
        "",
        "  reset_process : process",
        "  begin",
        "    reset_i <= '1';",
        "    wait for 5 * CLK_PERIOD;",
        "    wait until rising_edge(clock_i);",
        "    reset_i <= '0';",
        "    wait;",
        "  end process;",
        "",
        "  stimulus : process",
        "  begin",
        "    test_runner_setup(runner, runner_cfg);",
        "",
        "    if run(\"main\") then",
        "      wait until reset_i = '0';",
        "      wait until rising_edge(clock_i);",
        "",
        "      for bit_index in 0 to LDPC_K - 1 loop",
        "        data_i <= MESSAGE_BITS(bit_index);",
        "        data_en_i <= '1';",
        "        if bit_index = 0 then",
        "          data_start_i <= '1';",
        "        else",
        "          data_start_i <= '0';",
        "        end if;",
        "        wait until rising_edge(clock_i);",
        "      end loop;",
        "",
        "      data_i <= '0';",
        "      data_en_i <= '0';",
        "      data_start_i <= '0';",
        "",
        "      wait until frame_done = '1';",
        "      wait until rising_edge(clock_i);",
        "      info(\"TB LATENCY: total_cycles=\" & integer'image(frame_done_cycle - input_start_cycle) &",
        "           \", output_start_cycles=\" & integer'image(first_output_cycle - input_start_cycle) &",
        "           \", output_stream_cycles=\" & integer'image(frame_done_cycle - first_output_cycle + 1));",
        "      info(\"TB PASS: encoded frame matches reference vector\");",
        "    end if;",
        "",
        "    test_runner_cleanup(runner);",
        "    wait;",
        "  end process;",
        "",
        "  monitor : process (clock_i)",
        "  begin",
        "    if rising_edge(clock_i) then",
        "      if reset_i = '1' then",
        "        observed_index <= 0;",
        "        frame_done <= '0';",
        "        cycle_counter <= 0;",
        "        input_start_cycle <= 0;",
        "        first_output_cycle <= 0;",
        "        frame_done_cycle <= 0;",
        "        input_started <= '0';",
        "        first_output_seen <= '0';",
        "      else",
        "        cycle_counter <= cycle_counter + 1;",
        "",
        "        if input_started = '0' and data_en_i = '1' and data_start_i = '1' then",
        "          input_start_cycle <= cycle_counter;",
        "          input_started <= '1';",
        "        end if;",
        "",
        "        if first_output_seen = '0' and data_en_o = '1' then",
        "          first_output_cycle <= cycle_counter;",
        "          first_output_seen <= '1';",
        "        end if;",
        "",
        "        if data_en_o = '1' then",
        "          check(observed_index < LDPC_N, \"Observed more output bits than expected\");",
        "          check_equal(data_o, EXPECTED_CODEWORD(observed_index), \"Encoded bit mismatch at position \" & integer'image(observed_index));",
        "",
        "          if observed_index = 0 then",
        "            check_equal(data_start_o, '1', \"data_start_o must be asserted on the first output bit\");",
        "          else",
        "            check_equal(data_start_o, '0', \"data_start_o must only pulse on the first output bit\");",
        "          end if;",
        "",
        "          if observed_index < LDPC_K then",
        "            check_equal(data_message_o, '1', \"Message qualifier is incorrect during message output\");",
        "            check_equal(data_parity_o, '0', \"Parity qualifier is incorrect during message output\");",
        "          else",
        "            check_equal(data_message_o, '0', \"Message qualifier is incorrect during parity output\");",
        "            check_equal(data_parity_o, '1', \"Parity qualifier is incorrect during parity output\");",
        "          end if;",
        "",
        "          if observed_index = LDPC_N - 1 then",
        "            observed_index <= LDPC_N;",
        "            frame_done <= '1';",
        "            frame_done_cycle <= cycle_counter;",
        "          else",
        "            observed_index <= observed_index + 1;",
        "          end if;",
        "        end if;",
        "      end if;",
        "    end if;",
        "  end process;",
        "end architecture sim;",
        "",
    ]
    output_path.write_text("\n".join(lines), encoding="ascii")


def emit_wave_script(config: dict[str, int | str], output_path: Path) -> None:
    suffix = str(config["suffix"])
    lines = [
        "quietly WaveActivateNextPane {} 0",
        "",
        "add wave -noupdate -divider {tb}",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/clock_i",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/reset_i",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/data_i",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/data_en_i",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/data_start_i",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/data_o",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/data_en_o",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/data_start_o",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/data_message_o",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/data_parity_o",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/observed_index",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/frame_done",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/cycle_counter",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/input_start_cycle",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/first_output_cycle",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/frame_done_cycle",
        "",
        "add wave -noupdate -divider {wrapper}",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/dut/rom_row_block_s",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/dut/rom_data_s",
        "",
        "add wave -noupdate -divider {core io}",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/dut/core_inst/clock_i",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/dut/core_inst/reset_i",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/dut/core_inst/data_i",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/dut/core_inst/data_en_i",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/dut/core_inst/data_start_i",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/dut/core_inst/data_o_s",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/dut/core_inst/data_en_o_s",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/dut/core_inst/data_start_o_s",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/dut/core_inst/data_message_o_s",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/dut/core_inst/data_parity_o_s",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/dut/core_inst/message_pipe_bit_s",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/dut/core_inst/message_pipe_valid_s",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/dut/core_inst/message_pipe_start_s",
        "",
        "add wave -noupdate -divider {core control}",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/dut/core_inst/input_bit_count_s",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/dut/core_inst/input_row_block_s",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/dut/core_inst/input_local_index_s",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/dut/core_inst/parity_pending_s",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/dut/core_inst/parity_active_s",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/dut/core_inst/parity_block_index_s",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/dut/core_inst/parity_local_index_s",
        "",
        "add wave -noupdate -divider {core vectors}",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/dut/core_inst/rom_data_i",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/dut/core_inst/shift_registers_s",
        f"add wave -position insertpoint sim:/tb_ldpc_encoder_{suffix}/dut/core_inst/parity_blocks_s",
        "",
        "TreeUpdate [SetDefaultTree]",
        "WaveRestoreCursors {{Cursor 1} {0 ps} 0}",
        "configure wave -namecolwidth 320",
        "configure wave -valuecolwidth 120",
        "configure wave -justifyvalue left",
        "configure wave -signalnamewidth 1",
        "configure wave -timelineunits ns",
        "update",
        "",
    ]
    output_path.write_text("\n".join(lines), encoding="ascii")


def emit_compile_script(config: dict[str, int | str], output_path: Path) -> None:
    suffix = str(config["suffix"])
    sim_time_us = int(config["sim_time_us"])
    lines = [
        "onerror {quit -code 1 -f}",
        "onbreak {quit -code 1 -f}",
        "",
        f"if {{[catch {{exec python generate_ldpc_artifacts.py {suffix}}} result]}} {{",
        "  puts $result",
        "  quit -code 1 -f",
        "}",
        "",
        "if {[catch {exec gcc -O2 -std=c99 -o generate_vectors.exe generate_vectors.c} result]} {",
        "  puts $result",
        "  quit -code 1 -f",
        "}",
        "",
        f"if {{[catch {{exec ./generate_vectors.exe {suffix}}} result]}} {{",
        "  puts $result",
        "  quit -code 1 -f",
        "}",
        "",
        "if {[file exists work]} {",
        "  vdel -lib work -all",
        "}",
        "",
        "vlib work",
        "vmap work work",
        "",
        "vcom -2008 ../src/ldpc_encoder_common_pkg.vhd",
        "vcom -2008 ../src/ldpc_qc_encoder_core.vhd",
        f"vcom -2008 ../src/ldpc_encoder_{suffix}_config_pkg.vhd",
        f"vcom -2008 ../src/ldpc_encoder_{suffix}_qc_rom_pkg.vhd",
        f"vcom -2008 ../src/ldpc_encoder_{suffix}.vhd",
        f"vcom -2008 ../tb/ldpc_encoder_{suffix}_vectors_pkg.vhd",
        f"vcom -2008 ../tb/tb_ldpc_encoder_{suffix}.vhd",
        "",
        f"vsim -voptargs=+acc work.tb_ldpc_encoder_{suffix}",
        f"do wave_{suffix}.do",
        f"run {sim_time_us} us",
        "",
        "if {![info exists ::compile_all_running]} {",
        "  quit -f",
        "}",
        "",
    ]
    output_path.write_text("\n".join(lines), encoding="ascii")


def emit_run_py(output_path: Path) -> None:
    lines = [
        "from pathlib import Path",
        "from vunit import VUnit",
        "",
        "ROOT = Path(__file__).parent / \"../\"",
        "",
        "VU = VUnit.from_argv()",
        "VU.add_vhdl_builtins()",
        "",
        "LIB = VU.library(\"vunit_lib\")",
        "LIB.add_source_files(ROOT / \"src\" / \"*.vhd\")",
        "LIB.add_source_files(ROOT / \"tb\" / \"ldpc_encoder_*_vectors_pkg.vhd\")",
        "LIB.add_source_files(ROOT / \"tb\" / \"tb_vunit_ldpc_encoder_*.vhd\")",
        "",
        "VU.set_sim_option(\"modelsim.vsim_flags\", [\"-voptargs=\\\"+acc\\\"\"])",
        "VU.main()",
        "",
    ]
    output_path.write_text("\n".join(lines), encoding="ascii")


def emit_compile_alias(output_path: Path) -> None:
    output_path.write_text("onerror {quit -code 1 -f}\nonbreak {quit -code 1 -f}\n\ndo compile_1k_12.do\n", encoding="ascii")


def emit_wave_alias(output_path: Path) -> None:
    output_path.write_text("do wave_1k_12.do\n", encoding="ascii")


def emit_compile_all(configs: tuple[dict[str, int | str], ...], output_path: Path) -> None:
    lines = [
        "onerror {quit -code 1 -f}",
        "onbreak {quit -code 1 -f}",
        "",
        "set ::compile_all_running 1",
        "",
    ]
    for config in configs:
        suffix = str(config["suffix"])
        lines.append(f"puts \"Running compile_{suffix}.do\"")
        lines.append(f"do compile_{suffix}.do")
        lines.append("")
    lines.extend([
        "unset ::compile_all_running",
        "quit -f",
        "",
    ])
    output_path.write_text("\n".join(lines), encoding="ascii")


def main() -> int:
    args = parse_args()
    script_dir = Path(__file__).resolve().parent
    version_dir = script_dir.parent
    src_dir = version_dir / "src"
    tb_dir = version_dir / "tb"
    sim_dir = version_dir / "sim"

    requested_targets = set(args.targets)
    for config in CONFIGS:
        suffix = str(config["suffix"])
        if requested_targets and suffix not in requested_targets:
            continue

        info_length = int(config["info_length"])
        emit_config_package(config, src_dir / f"ldpc_encoder_{suffix}_config_pkg.vhd")
        emit_wrapper(config, src_dir / f"ldpc_encoder_{suffix}.vhd")
        emit_standard_testbench(config, tb_dir / f"tb_ldpc_encoder_{suffix}.vhd")
        emit_vunit_testbench(config, tb_dir / f"tb_vunit_ldpc_encoder_{suffix}.vhd")
        emit_wave_script(config, sim_dir / f"wave_{suffix}.do")
        emit_compile_script(config, sim_dir / f"compile_{suffix}.do")
        print(f"Generated static metadata files for {suffix}")

    emit_compile_all(CONFIGS, sim_dir / "compile_all.do")
    emit_compile_alias(sim_dir / "compile.do")
    emit_wave_alias(sim_dir / "wave.do")
    emit_run_py(sim_dir / "run.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())