/*
 * analyze_H_column.c
 *
 * Reads an Octave sparse matrix produced by build_h.c
 * and computes minimum row reuse distance for each column.
 *
 * Output example:
 *   reuse_H_1_2_4096.txt
 *
 * Compile:
 *   gcc -O3 -Wall -Wextra -std=c11 -o analyze_H_column analyze_H_column.c
 *
 * Run:
 *   ./analyze_H_column H_1_2_4096.mat
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <limits.h>

typedef struct {
    uint32_t row;
    uint32_t col;
} Entry;

static void die(const char *msg)
{
    fprintf(stderr, "Error: %s\n", msg);
    exit(EXIT_FAILURE);
}

static char *extract_filename_only(char *path)
{
    char *p1 = strrchr(path, '/');
    char *p2 = strrchr(path, '\\');

    char *p = p1 > p2 ? p1 : p2;

    return p ? (p + 1) : path;
}

int main(int argc, char **argv)
{
    FILE *fp;
    char line[256];

    int rows = 0;
    int cols = 0;

    unsigned long long nnz = 0;
    unsigned long long idx = 0;

    Entry *entries = NULL;

    uint32_t *last_row;
    uint32_t *min_distance;
    uint32_t *access_count;

    char output_filename[256];

    if (argc != 2) {
        fprintf(stderr, "Usage: %s H_matrix.mat\n", argv[0]);
        return EXIT_FAILURE;
    }

    fp = fopen(argv[1], "r");
    if (!fp) {
        die("cannot open input matrix file");
    }

    /* Parse header */
    while (fgets(line, sizeof(line), fp)) {

        if (strncmp(line, "# nnz:", 6) == 0) {

            char *p = strchr(line, ':');

            if (p != NULL) {
                nnz = strtoull(p + 1, NULL, 10);
            }
        }

        if (strncmp(line, "# rows:", 7) == 0) {
            sscanf(line, "# rows: %d", &rows);
        }

        if (strncmp(line, "# columns:", 10) == 0) {
            sscanf(line, "# columns: %d", &cols);

            /* after this, data lines begin */
            break;
        }
    }

    if (rows <= 0 || cols <= 0 || nnz == 0) {
        die("invalid matrix metadata");
    }

    entries = (Entry *)malloc((size_t)nnz * sizeof(Entry));
    if (!entries) {
        die("out of memory");
    }

    /* Read sparse entries */
    while (idx < nnz && fgets(line, sizeof(line), fp)) {

        uint32_t r, c;
        int val;

        if (sscanf(line, "%u %u %d", &r, &c, &val) == 3) {

            /* Convert to zero-based */
            entries[idx].row = r - 1;
            entries[idx].col = c - 1;

            idx++;
        }
    }

    fclose(fp);

    if (idx != nnz) {
        die("matrix file truncated");
    }

    last_row = (uint32_t *)malloc((size_t)cols * sizeof(uint32_t));
    min_distance = (uint32_t *)malloc((size_t)cols * sizeof(uint32_t));
    access_count = (uint32_t *)malloc((size_t)cols * sizeof(uint32_t));

    if (!last_row || !min_distance || !access_count) {
        die("out of memory");
    }

    for (int c = 0; c < cols; c++) {
        last_row[c] = UINT_MAX;
        min_distance[c] = UINT_MAX;
        access_count[c] = 0;
    }

    /*
     * Scan entries row-by-row.
     * The matrix generated by build_h.c is sorted by column,
     * therefore we perform a logical row traversal here.
     */

    for (uint32_t current_row = 0;
         current_row < (uint32_t)rows;
         current_row++) {

        for (unsigned long long i = 0; i < nnz; i++) {

            if (entries[i].row == current_row) {

                uint32_t c = entries[i].col;

                if (last_row[c] != UINT_MAX) {

                    uint32_t dist =
                        current_row - last_row[c];

                    if (dist < min_distance[c]) {
                        min_distance[c] = dist;
                    }
                }

                last_row[c] = current_row;
                access_count[c]++;
            }
        }
    }

    /* Build output filename */
    {
        char *base = extract_filename_only(argv[1]);

        snprintf(output_filename,
                 sizeof(output_filename),
                 "reuse_%s",
                 base);

        /* remove .mat if present */
        char *dot = strstr(output_filename, ".mat");
        if (dot) {
            *dot = '\0';
        }

        strcat(output_filename, ".txt");
    }

    FILE *out = fopen(output_filename, "w");
    if (!out) {
        die("cannot create output file");
    }

    fprintf(out, "Column reuse distance analysis\n");
    fprintf(out, "Input matrix: %s\n", argv[1]);
    fprintf(out, "Rows: %d\n", rows);
    fprintf(out, "Columns: %d\n", cols);
    fprintf(out, "NNZ: %llu\n\n", nnz);

    fprintf(out,
            "Column  Accesses  MinRowDistance\n");

    fprintf(out,
            "---------------------------------\n");

    uint32_t global_min = UINT_MAX;
    uint32_t global_max = 0;

    for (int c = 0; c < cols; c++) {

        if (min_distance[c] == UINT_MAX) {

            fprintf(out,
                    "%6d  %8u  %s\n",
                    c,
                    access_count[c],
                    "N/A");

        } else {

            fprintf(out,
                    "%6d  %8u  %u\n",
                    c,
                    access_count[c],
                    min_distance[c]);

            if (min_distance[c] < global_min) {
                global_min = min_distance[c];
            }

            if (min_distance[c] > global_max) {
                global_max = min_distance[c];
            }
        }
    }

    fprintf(out, "\n");

    fprintf(out,
            "Global minimum reuse distance: %u\n",
            global_min);

    fprintf(out,
            "Global maximum reuse distance: %u\n",
            global_max);

    fclose(out);

    printf("Analysis saved to %s\n",
           output_filename);

    free(entries);
    free(last_row);
    free(min_distance);
    free(access_count);

    return 0;
}